export const TRIGGER_LOGIN = 'TRIGGER_LOGIN'
export const TRIGGER_LOGIN_SUCCESS = 'TRIGGER_LOGIN_SUCCESS'
export const TRIGGER_LOGIN_FAILED = 'TRIGGER_LOGIN_FAILED'

export const TRIGGER_LOGOUT = 'TRIGGER_LOGOUT'
export const TRIGGER_LOGOUT_SUCCESS = 'TRIGGER_LOGOUT_SUCCESS'
export const TRIGGER_LOGOUT_FAILED = 'TRIGGER_LOGOUT_FAILED'

export const TRIGGER_REGISTER = 'TRIGGER_REGISTER'
export const TRIGGER_REGISTER_SUCCESS = 'TRIGGER_REGISTER_SUCCESS'
export const TRIGGER_REGISTER_FAILED = 'TRIGGER_REGISTER_FAILED'

export const TRIGGER_SET_PASSWORD = 'TRIGGER_SET_PASSWORD'
export const TRIGGER_SET_PASSWORD_SUCCESS = 'TRIGGER_SET_PASSWORD_SUCCESS'
export const TRIGGER_SET_PASSWORD_FAILED = 'TRIGGER_SET_PASSWORD_FAILED'

export const TRIGGER_CHANGE_PASSWORD = 'TRIGGER_CHANGE_PASSWORD'
export const TRIGGER_CHANGE_PASSWORD_SUCCESS = 'TRIGGER_CHANGE_PASSWORD_SUCCESS'
export const TRIGGER_CHANGE_PASSWORD_FAILED = 'TRIGGER_CHANGE_PASSWORD_FAILED'

export const TRIGGER_FORGET_PASSWORD = 'TRIGGER_FORGET_PASSWORD'
export const TRIGGER_FORGET_PASSWORD_SUCCESS = 'TRIGGER_FORGET_PASSWORD_SUCCESS'
export const TRIGGER_FORGET_PASSWORD_FAILED = 'TRIGGER_FORGET_PASSWORD_FAILED'

export const TRIGGER_SEARCH_KEYWORD = 'TRIGGER_SEARCH_KEYWORD'

